enum KEY {
    A = "KeyA",
    B = "KeyB",
    C = "KeyC",
    D = "KeyD",
    E = "KeyE",
    F = "KeyF",
    G = "KeyG",
    H = "KeyH",
    I = "KeyI",
    J = "KeyJ",
    K = "KeyK",
    L = "KeyL",
    M = "KeyM",
    N = "KeyN",
    O = "KeyO",
    P = "KeyP",
    Q = "KeyQ",
    R = "KeyR",
    S = "KeyS",
    T = "KeyT",
    U = "KeyU",
    V = "KeyV",
    W = "KeyW",
    X = "KeyX",
    Y = "KeyY",
    Z = "KeyZ",
    /*
    1 = "Key1",
    2 = "Key2",
    3 = "Key3",
    4 = "Key4",
    5 = "Key5",
    6 = "Key6",
    7 = "Key7",
    8 = "Key8",
    9 = "Key9",
    0 = "Key0",
    
    COMMA = "Key,",
    DOT = "Key.",
    MINUS = "Key-",
    SLASH = "Key/",
    ?="Key?",
    +="Key+",
    != "Key!",
    @="Key@",
    #="Key#",
    $ = "Key$",
    %= "Key%",
    ^= "Key^",
    &= "Key&",
    *= "Key*",
    OpenBracket = "Key(",
    ClosingBracket = "Key)" 
    */
}